name: terraform
on: push
env:
  AWS_REGION: "ap-northeast-1"
  TF_VERSION: "1.9.3"
  TF_VAR_aws_region: "ap-northeast-1"
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: init
        run: terraform init
      - name: Terraform fmt
        run: terraform fmt
      - name: Terraform plan
        run: terraform plan
      - name: Terraform apply
        run: terraform apply
