name: terraform
on: push
env:
  AWS_REGION: "ap-northeast-1"
  TF_VERSION: "1.9.3"
  TF_VAR_aws_region: "ap-northeast-1"
jobs:
  hello:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
      SA_ACCOUNT: ${{ secrets.SA_ACCOUNT }}
      WI_PROVIDER: ${{ secrets.WI_PROVIDER }}
    steps:
      - uses: 'actions/checkout@v4'
      - id: 'gcpauth'
        uses: google-github-actions/auth@v2
        with:
          project_id: "${{ env.GCP_PROJECT }}"
          service_account: "${{ env.SA_ACCOUNT }}"
          workload_identity_provider: "${{ env.WI_PROVIDER }}"
      - uses: google-github-actions/setup-gcloud@v2
      - run: gcloud storage ls gs://
