name: terraform
on: push
env:
  AWS_REGION: "ap-northeast-1"
  TF_VERSION: "1.9.3"
  TF_VAR_aws_region: "ap-northeast-1"
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  SA_ACCOUNT: ${{ secrets.SA_ACCOUNT }}
  WI_PROVIDER: ${{ secrets.WI_PROVIDER }}
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.GCP_PROJECT }}
          workload_identity_provider: ${{ env.WI_PROVIDER }}
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: init
        run: terraform init
      - name: Terraform fmt
        run: terraform fmt
      - name: Terraform plan
        run: terraform plan
      - name: Terraform apply
        run: terraform apply
