name: terraform
on: push
env:
  AWS_REGION: "ap-northeast-1"
  TF_VERSION: "1.9.3"
  TF_VAR_aws_region: "ap-northeast-1"
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  SA_ACCOUNT: ${{ secrets.SA_ACCOUNT }}
  WI_PROVIDER: ${{ secrets.WI_PROVIDER }}
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/auth@v2
        with:
          service_account: '${{ env.SA_ACCOUNT }}'
          workload_identity_provider: '${{ env.WI_PROVIDER }}'
