name: terraform
on: push
env:
  AWS_REGION: "ap-northeast-1"
  TF_VERSION: "1.9.3"
  TF_VAR_aws_region: "ap-northeast-1"
jobs:
  hello:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
      SA_ACCOUNT: ${{ secrets.SA_ACCOUNT }}
      WI_PROVIDER: ${{ secrets.WI_PROVIDER }}
    steps:
      - uses: 'actions/checkout@v4'
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          project_id: "${{ env.GCP_PROJECT }}"
          service_account: "${{ env.SA_ACCOUNT }}"
          workload_identity_provider: "${{ env.WI_PROVIDER }}"
      - name: init
        run: terraform init
      - name: Terraform plan
        run: terraform plan
      - name: Terraform apply
        run: terraform apply -auto-approve

